# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 10.15
        uses: actions/setup-node@v2
        with:
          node-version: 10.15
          cache: 'npm'
      - run: npm i
      - run: npm run build:prod

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
